/// AUTO GENERATED BY build.rs

use std::collections::HashMap;
use webrender_build::shader::ShaderId;

#[derive(Debug, Copy, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
#[cfg_attr(feature = "serialize_program", derive(Deserialize, Serialize))]
pub struct SourceWithId {{
    pub source: &'static str,
    pub id: ShaderId,
}}

lazy_static! {{
    pub static ref SHADERS: HashMap<&'static str, SourceWithId> = {{
        let mut h = HashMap::new();
        // Following statements are auto-generated by the build.rs script
{}
        h
    }};
}}
