[configs]
skip-check-length = false
skip-check-licenses = false
check-alphabetical-order = false

[ignore]
# Ignored packages with duplicated versions
packages = [
    # wrench uses 0.14, glean-core uses 0.12
    "android_log-sys",
    "android_logger",
    # transition to bitflags 2 is underway.
    "bitflags",
    "cfg-if",
    "core-foundation",
    "core-foundation-sys",
    "core-graphics",
    # requires a new version of font-loader, see https://github.com/matprec/rust-font-loader/pull/36
    "core-text",
    # derive_more 0.99 is required by glsl-lang
    "derive_more",
    # core-text 20.x uses foreign-types 0.5, core-graphics 0.22 uses 0.3
    "foreign-types",
    "foreign-types-shared",
    # Several crates depend on 0.2.6, and jobserver depends on 0.3.3.
    "getrandom",
    # polling 3.x requires 0.5, atty/num_cpus require 0.1
    "hermit-abi",
    # Internal dependencies of glsl-lang (only used in wrench) require different versions.
    "hashbrown",
    # glsl requires 5.1, and xcursor (required by winit) requires 7.1.
    # when a version of glsl depending on 7.1 is published we can update.
    "nom",
    # glutin 0.32 (via dispatch2) uses objc2 0.6, winit 0.30 uses 0.5
    "objc2",
    "objc2-app-kit",
    "objc2-foundation",
    "rand",
    "rand_core",
    # Multiple versions needed by different transitive deps
    "redox_syscall",
    # rinja (dependency of uniffi) requires 2.1, rowan requires 1.1
    "rustc-hash",
    # calloop/sctk/winit use 0.38, wayland-backend/polling use 1.x
    "rustix",
    # glsl-lang uses 0.1, winit uses 0.2
    "smol_str",
    # transition to syn 2 is underway.
    "syn",
    # Requires an update to clap v4
    "textwrap",
    # v1 required by glsl-lang@0.2
    # v2 by Glean and rkv
    "thiserror",
    "thiserror-impl",
    # v1 required by clap@3, which wrench uses
    # v2 required by uniffi (transitive of Glean)
    "indexmap",
    # Can be fixed by removing time dependency - see bug 1765324
    "wasi",
    # android-activity uses 0.4, ndk/ndk-sys use 0.3
    "jni-sys",
    # rustix 1.x uses 0.12, rustix 0.38.x uses 0.4
    "linux-raw-sys",
    "windows_i686_gnu",
    "windows_x86_64_msvc",
    "windows_x86_64_gnullvm",
    "windows_x86_64_gnu",
    "regex-syntax",
    "windows-targets",
    "windows-sys",
    "windows_aarch64_msvc",
    "windows_i686_msvc",
    "windows_aarch64_gnullvm",
    "miniz_oxide",
    # 0.9 required by glean/uniffi
    # 0.5 by proc-macro-crate
    "toml",
    "windows-link",
]

# Files that are ignored for all tidy and lint checks.
files = [
    "./wrench/src/egl.rs",  # Copied from glutin
]

# Many directories are currently ignored while we tidy things up
# gradually.
directories = [
   # Generated and upstream code combined with our own. Could use cleanup
  "./target",
  "./webrender/src",
]
