[package]
name = "wr_glyph_rasterizer"
version = "0.1.0"
authors = ["The Mozilla Project Developers"]
description = "A glyph rasterizer for WebRender"
license = "MPL-2.0"
edition = "2018"

[features]
default = ["static_freetype"]
dynamic_freetype = []
static_freetype = ["freetype/freetype-sys"]
capture = ["api/serialize", "serde", "smallvec/serde"]
replay = ["api/deserialize", "serde", "smallvec/serde"]
gecko = ["firefox-on-glean", "glean"]

[dependencies]
api = { version = "0.62.0", path = "../webrender_api", package = "webrender_api" }
euclid = { version = "0.22.0", features = ["serde"] }
malloc_size_of = { version = "0.0.2", path = "../wr_malloc_size_of", package = "wr_malloc_size_of" }
malloc_size_of_derive = "0.1"
rayon = "1"
smallvec = "1"
tracy-rs = "0.1.2"
log = "0.4"
lazy_static = "1"
fxhash = "0.2.1"
glean = { version = "58.1.0", optional = true }
firefox-on-glean = { version = "0.1.0", optional = true }
serde = { optional = true, version = "1.0", features = ["serde_derive"] }

[dev-dependencies]
env_logger = { version = "0.10", default_features = false }
euclid = "0.22"
gleam = "0.15"
glutin = "0.28"
rayon = "1"
winit = "0.26"

[target.'cfg(any(target_os = "android", all(unix, not(any(target_os = "macos", target_os = "ios")))))'.dependencies]
freetype = { version = "0.7", default-features = false }
libc = "0.2"

[target.'cfg(target_os = "windows")'.dependencies]
dwrote = "0.11"

[target.'cfg(any(target_os = "macos", target_os = "ios"))'.dependencies]
core-foundation = "0.9.2"
core-graphics = "0.23"
core-text = { version = "20.1", default-features = false }
objc = "0.2"
