[package]
name = "webrender-examples"
version = "0.1.0"
authors = ["Glenn Watson <gw@intuitionlibrary.com>"]
license = "MPL-2.0"
repository = "https://github.com/zng-ui/zng-webrender"
edition = "2018"

[[bin]]
name = "alpha_perf"
path = "alpha_perf.rs"

[[bin]]
name = "animation"
path = "animation.rs"

[[bin]]
name = "basic"
path = "basic.rs"

[[bin]]
name = "blob"
path = "blob.rs"

[[bin]]
name = "document"
path = "document.rs"

[[bin]]
name = "iframe"
path = "iframe.rs"

[[bin]]
name = "image_resize"
path = "image_resize.rs"

[[bin]]
name = "multiwindow"
path = "multiwindow.rs"

[[bin]]
name = "scrolling"
path = "scrolling.rs"

[[bin]]
name = "texture_cache_stress"
path = "texture_cache_stress.rs"

[[bin]]
name = "yuv"
path = "yuv.rs"

[features]
debug = ["webrender/capture", "webrender/profiler"]

[dependencies]
app_units = "0.7"
env_logger = { version = "0.10", default-features = false }
euclid = "0.22"
gleam = "0.15"
glutin = "0.28"
rayon = "1"
webrender = { path = "../webrender", package = "zng-webrender" }
winit = "0.26"

[target.'cfg(target_os = "macos")'.dependencies]
core-foundation = "0.7"
